# Example configuration file
[settings]
nSteps = 100 # number of time steps
tStart = 0.2 # start time
tEnd = 0.5 # end time

[geometry]
meshName = "bay.msh"
oilSpillCenter = [0.35, 0.45]
borders = [ [0.0, 0.45], [0.0, 0.2] ] # define where fish are located
logName = "log" # name of the log file created

[IO] 
writeFrequency = 10 # Frequency of output video. If not provided, no video is recorded. restartFile "input/solution.txt" # Restart file must be provided if start time is provided.